metadata_wizard --service localhost:8000 --scope table --dataplex_project_id jsk-dataplex-demo-380508 --llm_location us-central1 --dataplex_location us-central1 --table_project_id jsk-dataplex-demo-380508 --table_dataset_id car_crashes --table_id accident --debug TRUE
pip uninstall dataplexutils_metadata_wizard metadata_wizard
metadata_wizard --service localhost:8000 --scope dataset --dataplex_project_id jsk-dataplex-demo-380508 --llm_location us-central1 --dataplex_location us-central1 --table_project_id jsk-dataplex-demo-380508 --table_dataset_id car_crashes --table_id accident --debug TRUE --documentation_uri "gs://wizard-documents/Data 360 Documentation - Dataflix - olderdocs.pdf" --strategy NAIVE


metadata_wizard --service localhost:8000 --scope dataset_columns --dataplex_project_id jsk-dataplex-demo-380508 --llm_location us-central1 --dataplex_location us-central1 --table_project_id jsk-dataplex-demo-380508 --table_dataset_id car_crashes --table_id accident --debug TRUE --documentation_csv_uri "gs://wizard-documents/metadata_wizard_demo - Sheet1.csv" --strategy DOCUMENTED


metadata_wizard --service localhost:8000 --scope dataset_columns --dataplex_project_id jsk-dataplex-demo-380508 --llm_location us-central1 --dataplex_location us-central1 --table_project_id jsk-dataplex-demo-380508 --table_dataset_id car_crashes --table_id accident --debug TRUE --documentation_csv_uri "gs://wizard-documents/metadata_wizard_demo - Sheet1.csv" --strategy DOCUMENTED --use_lineage_tables TRUE --use_lineage_processes TRUE --use_profile TRUE --use_data_quality TRUE --use_ext_documents TRUE 

metadata_wizard --service localhost:8000 --scope columns --dataplex_project_id jsk-dataplex-demo-380508 --llm_location us-central1 --dataplex_location us-central1 --table_project_id jsk-dataplex-demo-380508 --table_dataset_id car_crashes --table_id cevent --debug TRUE --documentation_uri "gs://wizard-documents/Data 360 Documentation - Dataflix - olderdocs.pdf" --use_lineage_tables TRUE --use_lineage_processes TRUE --use_profile TRUE --use_data_quality TRUE --use_ext_documents TRUE 
metadata_wizard --service localhost:8000 --scope table --dataplex_project_id jsk-dataplex-demo-380508 --llm_location us-central1 --dataplex_location us-central1 --table_project_id jsk-dataplex-demo-380508 --table_dataset_id car_crashes --table_id cevent --debug TRUE --documentation_uri "gs://wizard-documents/Data 360 Documentation - Dataflix - olderdocs.pdf" --use_lineage_tables TRUE --use_lineage_processes TRUE --use_profile TRUE --use_data_quality TRUE --use_ext_documents TRUE 

metadata_wizard --service localhost:8000 --scope columns --dataplex_project_id jsk-dataplex-demo-380508 --llm_location us-central1 --dataplex_location us-central1 --table_project_id jsk-dataplex-demo-380508 --table_dataset_id car_crashes --table_id accident --debug TRUE --documentation_uri "gs://wizard-documents/Data 360 Documentation - Dataflix - olderdocs.pdf" --use_lineage_tables TRUE --use_lineage_processes TRUE --use_profile TRUE --use_data_quality TRUE --use_ext_documents TRUE 
metadata_wizard --service localhost:8000 --scope table --dataplex_project_id jsk-dataplex-demo-380508 --llm_location us-central1 --dataplex_location us-central1 --table_project_id jsk-dataplex-demo-380508 --table_dataset_id car_crashes --table_id accident --debug TRUE --documentation_uri "gs://wizard-documents/Data 360 Documentation - Dataflix - olderdocs.pdf" --use_lineage_tables TRUE --use_lineage_processes TRUE --use_profile TRUE --use_data_quality TRUE --use_ext_documents TRUE 

metadata_wizard --service localhost:8000 --scope columns --dataplex_project_id jsk-dataplex-demo-380508 --llm_location us-central1 --dataplex_location us-central1 --table_project_id jsk-dataplex-demo-380508 --table_dataset_id car_crashes --table_id drugs --debug TRUE --documentation_uri "gs://wizard-documents/Data 360 Documentation - Dataflix - olderdocs.pdf" --use_lineage_tables TRUE --use_lineage_processes TRUE --use_profile TRUE --use_data_quality TRUE --use_ext_documents TRUE 
metadata_wizard --service localhost:8000 --scope table --dataplex_project_id jsk-dataplex-demo-380508 --llm_location us-central1 --dataplex_location us-central1 --table_project_id jsk-dataplex-demo-380508 --table_dataset_id car_crashes --table_id damage --debug TRUE --documentation_uri "gs://wizard-documents/Data 360 Documentation - Dataflix - olderdocs.pdf" --use_lineage_tables TRUE --use_lineage_processes TRUE --use_profile TRUE --use_data_quality TRUE --use_ext_documents TRUE 

metadata_wizard --service localhost:8000 --scope dataset_columns --dataplex_project_id jsk-dataplex-demo-380508 \
--llm_location us-central1 --dataplex_location us-central1 --table_project_id jsk-dataplex-demo-380508 --table_dataset_id \
car_crashes --table_id person --debug TRUE \
--documentation_csv_uri "gs://wizard-documents/metadata_wizard_demo - Sheet1.csv" --use_lineage_tables TRUE \
--use_lineage_processes TRUE --use_profile TRUE --use_data_quality TRUE --use_ext_documents TRUE 